make ptex, uptex, do not make eptex, euptex

diff --git a/.github/workflows/build-msvc.yml b/.github/workflows/build-msvc.yml
--- a/.github/workflows/build-msvc.yml
+++ b/.github/workflows/build-msvc.yml
@@ -191,6 +191,8 @@ jobs:
           echo ""
           ./tangle.exe --version || echo "tangle"
           echo ""
+          ./ctangle.exe --version || echo "ctangle"
+          echo ""
           ./ptex.exe --version || echo "ptex"
           echo ""
           ./uptex.exe --version || echo "uptex"
@@ -219,10 +221,10 @@ jobs:
           # $srcdir/cwebdir/cweave.test || echo "** failed: cweave.test"
           $srcdir/tiedir/tie.test     || echo "** failed: tie.test"
           $srcdir/ptexdir/pver.test     || echo "** failed: pver.test"
-          $srcdir/eptexdir/epver.test   || echo "** failed: epver.test"
+          # $srcdir/eptexdir/epver.test   || echo "** failed: epver.test"
           $srcdir/uptexdir/upver.test   || echo "** failed: upver.test"
           $srcdir/uptexdir/upkcat.test  || echo "** failed: upkcat.test"
-          $srcdir/eputexdir/eupver.test || echo "** failed: eupver.test"
+          # $srcdir/eputexdir/eupver.test || echo "** failed: eupver.test"
         env:
           srcroot: "../source"
           TEXMFCNF: "../source/texk/kpathsea/tests/windows"
