bibtex8*.test: add bibtex8u-mem.test

diff --git a/.github/workflows/build-msvc.yml b/.github/workflows/build-msvc.yml
--- a/.github/workflows/build-msvc.yml
+++ b/.github/workflows/build-msvc.yml
@@ -119,35 +119,17 @@ jobs:
           cd ./Work
           export BinDir=./Debug/bin ExeExt=.exe srcdir=../source/texk/bibtex-x
           $srcdir/tests/bibtex8.test       || echo -e "**\n** failed: bibtex8.test\n**"
+          $srcdir/tests/bibtexu.test       || echo -e "**\n** failed: bibtexu.test\n**"
+          $srcdir/tests/bibtex8u-mem.test  || echo -e "**\n** failed: bibtex8u-mem.test\n**"
           $srcdir/tests/bibtex8-char.test  || echo -e "**\n** failed: bibtex8-char.test\n**"
           $srcdir/tests/bibtex8-sort.test  || echo -e "**\n** failed: bibtex8-sort.test\n**"
-          $srcdir/tests/bibtexu.test       || echo -e "**\n** failed: bibtexu.test\n**"
           $srcdir/tests/bibtexu-basic.test || echo -e "**\n** failed: bibtexu-basic.test\n**"
           $srcdir/tests/bibtexu-range.test || echo -e "**\n** failed: bibtexu-range.test\n**"
           $srcdir/tests/bibtexu-char.test  || echo -e "**\n** failed: bibtexu-char.test\n**"
-          pwd
-          ./Debug/bin/kpsewhich.exe --format=bst --progname=bibtex8 --debug=16 88591lat.csf || echo ""
-          ./Debug/bin/kpsewhich.exe --format=bst --progname=bibtex8 --debug=16 sort1.csf || echo ""
-          ./Debug/bin/kpsewhich.exe --format=bst --progname=bibtex8 --debug=16 testperiod.bst || echo ""
-          ./Debug/bin/kpsewhich.exe --format=bst --progname=bibtex8 --debug=16 testchar.bst || echo ""
-          ./Debug/bin/kpsewhich.exe --format=bst --progname=bibtex8 --debug=16 testname.bst || echo ""
-        env:
-          srcroot: "../source"
-          TEXMFCNF: "../source/texk/kpathsea/tests/windows"
-          BIBINPUTS: ".;$srcroot/texk/web2c/tests;$srcroot/texk/bibtex-x/tests"
-          BSTINPUTS: ".;$srcroot/texk/tests/texmf;$srcroot/texk/web2c/tests;$srcroot/texk/bibtex-x/{tests,csf}"
-      - name: test bibtex-x, max_print_line=99
-        shell: bash
-        run: |
-          cd ./Work
-          export BinDir=./Debug/bin ExeExt=.exe srcdir=../source/texk/bibtex-x
           $srcdir/tests/bibtexu-sort.test  || echo -e "**\n** failed: bibtexu-sort.test\n**"
         env:
           srcroot: "../source"
           TEXMFCNF: "../source/texk/kpathsea/tests/windows"
-          BIBINPUTS: ".;$srcroot/texk/web2c/tests;$srcroot/texk/bibtex-x/tests"
-          BSTINPUTS: ".;$srcroot/texk/tests/texmf;$srcroot/texk/web2c/tests;$srcroot/texk/bibtex-x/{tests,csf}"
-          max_print_line: "99"
 
       - name: test dviout-util
         shell: bash
